module.exports = {
    SERVER_REQUEST_ERR: `Prázdna požiadavka`,
    SERVER_PAGE_NOT_FOUND: `Je nám ľúto, ale požadovaná stránka nebola nájdená`,
    SERVER_VALIDATION_ERR: `Údaje boli nesprávne vyplnené`,
    MONGO_DATABASE_CONNECTED: `Mongo databáza pripojená, adresa:`,
    MONGO_DATABASE_DISCONNECTED: `Mongo databáza odpojená adresa:`,
    MONGO_DATABASE_CONNECTION_ERROR: `Pripojenie zlyhalo host: `,
    REDIS_DATABASE_CONNECTION_ERROR: `Nepodarilo sa pripojiť ku: `,
    DATABASE_SEED: `Databáza bola úspešne naplnená údajmi`,
    DATABASE_SEED_ERR: `Databázu sa nepodarilo naplniť údajmi`,
    AUTH_REQUIRED: `Ľutujeme, ale stránka nie je k dispozícií`,
    PROXY_ERR: `Služba je nedostupná`,
    AUTH_ERR: `Prístup odmietnutý`,

    CREATE_STATUS_ERR: `Vytvorenie nového státusu zásielky sa nepodarilo`,
    UPDATE_STATUS_ERR: `Aktualizácia státusu zásielky sa nepodarilo`,
    DELETE_STATUS_ERR: `Odstránenie státusu zásielky sa nepodarilo`,
    GET_STATUS_ERR: `Ľutujeme ale státus zásielky s identifikačním číslom neexistuje`,
    STATUS_NOT_FOUND: `Ľutujeme ale nenašiel sa žiadný státus zásielky`,

    CREATE_PRICE_ERR: `Vytvorenie cenníka sa nepodarilo`,
    UPDATE_PRICE_ERR: `Aktualizácia cenníka sa nepodarilo`,
    DELETE_PRICE_ERR: `Odstránenie cenníka sa nepodarilo`,
    GET_PRICE_ERR: `Ľutujeme, ale cenník neexistuje`,
    PRICE_NOT_FOUND: `Ľutujeme ale nenašiel sa žiadný cenník`,

    CREATE_INVOICE_ERR: `Vytvorenie faktúry sa nepodarilo, skúste znova`,
    UPDATE_INVOICE_ERR: `Aktualizácia faktúry sa nepodarilo, skúste znova`,
    DELETE_INVOICE_ERR: `Odstránenie faktúry sa nepodarilo, skúste znova`,
    GET_INVOICE_ERR: `Ľutujeme ale faktúra s identifikačním číslom neexistuje`,
    INVOICE_NOT_FOUND: `Ľutujeme ale nenašla sa žiadna fatúra`,

    CREATE_SHIPMENT_ERR: `Vytvorenie zásielky sa nepodarilo`,
    UPDATE_SHIPMENT_ERR: `Aktualizácia zásielky sa nepodarilo`,
    DELETE_SHIPMENT_ERR: `Odstránenie zásielky sa nepodarilo`,
    GET_SHIPMENT_ERR: `Ľutujeme ale zásielka s identifikačním číslom neexistuje`,
    SHIPMENT_NOT_FOUND: `Ľutujeme ale nenašiel sa žiadná zásielka`,

    STATUS_NAME_LENGHT: `Minimálna dlžka státusu zásielky je 3 a maximalná je 64`,
    STATUS_NAME_MATCHES: `Nesprávný formát státusu zásielky`,
    STATUS_MONGO_ID: `Nesprávný formát identifikacného čísla`,
    STATUS_PAGE_NUMBER_INT: `Nesprávný formát číslo strany`,
    STATUS_PAGE_SIZE_INT: `Nesprávný formát veľkosť strany`,
    STATUS_COLUMN_NAME_MATCHES: `Nesprávný formát názov stľpca`,
    STATUS_UNIQUE: `Státus zásielky už existuje`,

    SHIPMENT_COURIER_ID_INT: `Nesprávný formát identifikacného čísla kuriéra`,
    SHIPMENT_PARCEL_ID_INT: `Nesprávný formát identifikacného čísla balíka`,
    SHIPMENT_TO_LENGHT: `Minimálna dlžka názvu miesta dodania je 3 a maximalná je 64`,
    SHIPMENT_TO_MATHCES: `Nesprávný formát názvu miesta dodania`,
    SHIPMENT_FROM_LENGHT: `Minimálna dlžka názvu miesta je 3 a maximalná je 64`,
    SHIPMENT_FROM_MATHCES: `Nesprávný formát názvu miesta`,
    SHIPMENT_PRICE_FLOAT: `Nesprávný formát ceny zásielky`,
    SHIPMENT_EXPRESS_BOOLEAN: `Nesprávný formát hodnoty express dodania`,
    SHIPMENT_DATE: `Nesprávný formát dátumu`,
    SHIPMENT_MONGO_ID: `Nesprávný formát identifikacného čísla`,
    SHIPMENT_PAGE_NUMBER_INT: `Nesprávný formát číslo strany`,
    SHIPMENT_COLUMN_NAME_MATCHES: `Nesprávný formát názov stľpca`,
    SHIPMENT_PAGE_SIZE_INT: `Nesprávný formát veľkosť strany`,

    INVOICE_INVOICE_LENGHT: `Minimálna dlžka adresi faktúri je 3 a maximalná je 255`,
    INVOICE_INVOICE_MATCHES: `Nesprávný formát adresi pre faktúru`,
    INVOICE_PARCEL_ID_INT: `Nesprávný formát identifikacného čísla balíka`,
    INVOICE_ID_INT: `Nesprávný formát identifikacného čísla`,
    INVOICE_PAGE_NUMBER_INT: `Nesprávný formát číslo strany`,
    INVOICE_PAGE_SIZE_INT: `Nesprávný formát veľkosť strany`,
    INVOICE_COLUMN_NAME_ALPHA: `Nesprávný formát názov stľpca`,
    INVOICE_UNIQUE: `Faktúra už existuje, už bola vygenerovaná`,

    PRICES_PRICE_FLOAT: `Nesprávný formát ceny zásielky`,
    PRICE_MONGO_ID: `Nesprávný formát identifikacného čísla`,
};