module.exports = {
    SERVER_REQUEST_ERR: `Prázdna požiadavka`,
    SERVER_PAGE_NOT_FOUND: `Je nám ľúto, ale požadovaná stránka nebola nájdená`,
    SERVER_VALIDATION_ERR: `Údaje boli nesprávne vyplnené`,
    MONGO_DATABASE_CONNECTED: `Mongo databáza pripojená, adresa:`,
    MONGO_DATABASE_DISCONNECTED: `Mongo databáza odpojená adresa:`,
    MONGO_DATABASE_CONNECTION_ERROR: `Pripojenie zlyhalo host: `,
    REDIS_DATABASE_CONNECTION_ERROR: `Nepodarilo sa pripojiť ku: `,
    DATABASE_SEED: `Databáza bola úspešne naplnená údajmi`,
    DATABASE_SEED_ERR: `Databázu sa nepodarilo naplniť údajmi`,
    AUTH_REQUIRED: `Ľutujeme, ale stránka nie je k dispozícií`,
    AUTH_ERR: `Prístup odmietnutý`,

    CREATE_STATUS_ERR: `Vytvorenie nového státusu zásielky sa nepodarilo`,
    UPDATE_STATUS_ERR: `Aktualizácia státusu zásielky sa nepodarilo`,
    DELETE_STATUS_ERR: `Odstránenie státusu zásielky sa nepodarilo`,
    GET_STATUS_ERR: `Ľutujeme ale státus zásielky s identifikačním číslom neexistuje`,
    STATUS_NOT_FOUND: `Ľutujeme ale nenašiel sa žiadný státus zásielky`,

    CREATE_SHIPMENT_ERR: `Vytvorenie nového státusu balíka sa nepodarilo`,
    UPDATE_SHIPMENT_ERR: `Aktualizácia státusu balíka sa nepodarilo`,
    DELETE_SHIPMENT_ERR: `Odstránenie státusu balíka sa nepodarilo`,
    GET_SHIPMENT_ERR: `Ľutujeme ale státus balíka s identifikačním číslom neexistuje`,
    SHIPMENT_NOT_FOUND: `Ľutujeme ale nenašiel sa žiadný balík s státusom`,

    STATUS_NAME_LENGHT: `Minimálna dlžka státusu zásielky je 3 a maximalná je 64`,
    STATUS_NAME_ASCII: `Nesprávný formát státusu zásielky`,
    STATUS_MONGO_ID: `Nesprávný formát identifikacného čísla`,
    STATUS_PAGE_NUMBER_INT: `Nesprávný formát číslo strany`,
    STATUS_PAGE_SIZE_INT: `Nesprávný formát veľkosť strany`,
    STATUS_UNIQUE: `Státus zásielky už existuje`,

    SHIPMENT_COURIER_ID_INT: `Nesprávný formát identifikacného čísla kuriéra`,
    SHIPMENT_PARCEL_ID_INT: `Nesprávný formát identifikacného čísla balíka`,
    SHIPMENT_TO_LENGHT: `Minimálna dlžka názvu miesta dodania je 3 a maximalná je 64`,
    SHIPMENT_TO_ASCII: `Nesprávný formát názvu miesta dodania`,
    SHIPMENT_FROM_LENGHT: `Minimálna dlžka názvu miesta je 3 a maximalná je 64`,
    SHIPMENT_FROM_ASCII: `Nesprávný formát názvu miesta`,
    SHIPMENT_PRICE_FLOAT: `Nesprávný formát ceny zásielky`,
    SHIPMENT_EXPRESS_BOOLEAN: `Nesprávný formát hodnoty express dodania`,
    SHIPMENT_CONFIRMED_BOOLEAN: `Nesprávný formát hodnoty potvrdenia`,
    SHIPMENT_DATE: `Nesprávný formát dátumu`,
    SHIPMENT_MONGO_ID: `Nesprávný formát identifikacného čísla`,
    SHIPMENT_PAGE_NUMBER_INT: `Nesprávný formát číslo strany`,
    SHIPMENT_PAGE_SIZE_INT: `Nesprávný formát veľkosť strany`
};